
NAME:=  

SRCDIR:= srcs
OBJDIR:= objs
INCDIR:= includes

SRCS:= 
OBJS:= 
INCS:= 

AR:= ar
ARFLAGS:= -rcs

CC:= gcc
CFLAGS:= -Wall -Werror -Wextra


$(NAME):


all: $(NAME)


clean:


fclean: clean


re: fclean all


.PHONY: all clean fclean re
